### PR TITLE
Refactor/change api core path name

### PR DESCRIPTION
**Pull request by 1001Josias**
This PR aims to enhance the  structure semantics of the API.

Noting that the `routes` folder is not limited solely to route definitions but houses essential core modules of the API. To more accurately reflect this function, the folder has been renamed to `api`.

### CODE REVIEW

**Comment by edwinhern** [comment]
Please reference the comments on this PR: https://github.com/edwinhern/express-typescript-2024/pull/70

**Comment by 1001Josias** [comment]
> Please reference the comments on this PR: #70

I did exactly what was suggested in [this comment](https://github.com/edwinhern/express-typescript-2024/pull/70#issuecomment-1981847493) and rewritten the commits using the "Conventional Commits" extension.
In your opinion, what could I have missed?

**Comment by edwinhern** [comment]
Was looking for something more like this example: https://github.com/edwinhern/express-typescript-2024/tree/refactor-api-versioning

It's a concept idea but would rather have versioning inside the routes, rather than making version folder outside, since majority of time, only few routes are updated.

**Comment by 1001Josias** [comment]
> Was looking for something more like this example: https://github.com/edwinhern/express-typescript-2024/tree/refactor-api-versioning
> 
> It's a concept idea but would rather have versioning inside the routes, rather than making version folder outside, since majority of time, only few routes are updated.

Okay, I reverted the commit that added the versioning

**Comment by edwinhern** [comment]
LGTM!

**Pull request merged**
